### PR TITLE
Ubuntu based Dockerfile for Lind-Wasm

### PR DESCRIPTION
**Pull request by namanlalitnyu**
## Description
This PR consists of the changes as mentioned in this issue (Create Lind-Wasm Container): https://github.com/Lind-Project/lind-wasm/issues/8

Fixes # (issue)
The change is mainly about creating a Docker image for the LIND-Wasm project, which installs all the necessary modules and libraries required for running Lind-Wasm.

### Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
I tested this Dockerfile on the Lind server and verified it by running the "Hello World" program.
1. First, we need to build the Dockerfile, which will create a docker image: `docker build -t lind-wasm .`
2. We will run the docker image inside a container by running: `docker run -it lind-wasm /bin/bash`
3. Inorder to run the "Hello world" program, follow the steps mentioned in this Readme (https://github.com/Lind-Project/lind-wasm) 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, safeposix-rust)

### CODE REVIEW

**Comment by namanlalitnyu** [comment]
@yzhang71 @rennergade, requesting your review of these changes. 
Thanks!

**Comment by rennergade** [comment]
This looks good to me but I don't have a lot of knowledge here. Let's get @yashaswi2000 and @yzhang71 to approve.

**Review by yzhang71 — APPROVED** [review]
LGTM!

**Review by qianxichen233 — APPROVED** [review]

**Review by robinyuan1002 — APPROVED** [review]

**Review by yashaswi2000 — APPROVED** [review]
LGTM

**Review by rennergade — APPROVED** [review]
Approved. @yzhang71 should be good for you to merge

**Pull request merged**
